export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'


export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export const RECEIVE_PRODUCTS = 'GET_PRODUCTS'
export const RECEIVE_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'


export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const REQUEST_ORDERS = 'REQUEST_ORDERS'
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS'
export const RECEIVE_ORDERS_ERROR = 'RECEIVE_ORDERS_ERROR'

export const LOGOUT = 'LOGOUT'
export const SET_ADDRESS = 'SET_ADDRESS'
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS'