// export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'
// export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
// export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY'
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY'
export const CLEAR_CART = 'CLEAR_CART'
// export const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST'
// export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS'
// export const REMOVE_FROM_CART_ERROR = 'REMOVE_FROM_CART_ERROR'

// export const REFRESH_CART = 'REFRESH_CART'

// export const REQUEST_CART = 'REQUEST_CART'
// export const RECEIVE_CART_SUCCESS = 'RECEIVE_CART_SUCCESS'
// export const RECEIVE_CART_ERROR = 'RECEIVE_CART_ERROR'
