
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export const RECEIVE_PRODUCTS = 'GET_PRODUCTS'
export const RECEIVE_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'

export const RECEIVE_PRODUCTS_TEST = 'RECEIVE_PRODUCTS_TEST'