export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const REQUEST_ORDERS = 'REQUEST_ORDERS'
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS'
export const RECEIVE_ORDERS_ERROR = 'RECEIVE_ORDERS_ERROR'

export const REQUEST_WISHLIST = 'REQUEST_WISHLIST'
export const RECEIVE_WISHLIST = 'RECEIVE_WISHLIST'
export const RECEIVE_WISHLIST_ERROR = 'RECEIVE_WISHLIST_ERROR'

export const LOGOUT = 'LOGOUT'
export const SET_ADDRESS = 'SET_ADDRESS'
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS'


