export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const REQUEST_ORDERS = 'REQUEST_ORDERS'
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS'
export const RECEIVE_ORDERS_ERROR = 'RECEIVE_ORDERS_ERROR'

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST'
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST'
export const REQUEST_WISHLIST = 'REQUEST_WISHLIST'
export const RECEIVE_WISHLIST = 'RECEIVE_WISHLIST'
export const RECEIVE_WISHLIST_ERROR = 'RECEIVE_WISHLIST_ERROR'

export const LOGOUT = 'LOGOUT'
export const SET_ADDRESS = 'SET_ADDRESS'
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS'


export const REQUEST_REGISTER = 'REQUEST_REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'

